# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Service Bus Estimator - Stress Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RESOURCEGROUPNAME: 'ServiceBusEstimator'
  RESOURCEGROUPNAME_RECEIVERS: 'ServiceBusEstimatorReceivers'
  SERVICEBUSNAME: 'servicebusestimator-bus'
  LOCATION: 'eastus'
  ARM_TEMPLATES_PATH: 'src/Environment'
  ESTIMATOR_PACKAGE_PATH: 'src/AzureServiceBusEstimator'
  RECEIVER_PACKAGE_PATH: 'src/AzureServiceBusReceiver'
  DOTNET_VERSION: '6.0.x'
  MESSAGES: 5000
  MIN_SIZE: 1
  MAX_SIZE: 20
  NUMBER_OF_RECEIVERS: 2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build Estimator
        shell: bash
        run: |
          pushd './${{ env.ESTIMATOR_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Build Receiver
        shell: bash
        run: |
          pushd './${{ env.RECEIVER_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Resource Groups
        run: |
          if [ $(az group exists --name ${{ env.RESOURCEGROUPNAME }}) = false ]; then
            az group create -n ${{ env.RESOURCEGROUPNAME }} -l ${{ env.LOCATION }}
          fi
          if [ $(az group exists --name ${{ env.RESOURCEGROUPNAME_RECEIVERS }}) = false ]; then
            az group create -n ${{ env.RESOURCEGROUPNAME_RECEIVERS }} -l ${{ env.LOCATION }}
          fi

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDDHHmmss'

      - name: Deploy Azure resources
        uses: azure/arm-deploy@v1
        id: deployAzureResources
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTIONID }}
          resourceGroupName: ${{ env.RESOURCEGROUPNAME }}
          template: https://raw.githubusercontent.com/roberto-mardeni/azure-service-bus-premium-estimator/main/src/Environment/azuredeploy.json
          deploymentName: 'AzureDeploy-${{ steps.time.outputs.time }}'
          parameters: receiversResourceGroup=${{ env.RESOURCEGROUPNAME_RECEIVERS }} numberOfReceivers=${{ env.NUMBER_OF_RECEIVERS }}

      - name: Upload estimator artifact
        uses: actions/upload-artifact@v3
        with:
          name: estimator
          path: '${{ env.ESTIMATOR_PACKAGE_PATH }}/output'

      - name: Upload receiver artifact
        uses: actions/upload-artifact@v3
        with:
          name: receiver
          path: '${{ env.RECEIVER_PACKAGE_PATH }}/output'

      - name: Prepare Receivers Matrix
        id: set-matrix
        run: |
          matrix_list=$(src/Environment/create-matrix.sh ${{env.NUMBER_OF_RECEIVERS}})
          echo "Matrix List: $matrix_list"
          echo "::set-output name=matrix::[$matrix_list]"

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  deploy-estimator:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: estimator
          path: estimator

      - name: Deploy app
        uses: Azure/functions-action@v1
        id: deploy-estimator
        with:
          app-name: 'servicebusestimator-app'
          slot-name: 'Production'
          package: estimator

  deploy-receivers:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: ${{ fromJson(needs.build.outputs.matrix) }}
    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: receiver
          path: receiver

      - name: Deploy app
        uses: Azure/functions-action@v1
        with:
          app-name: 'servicebusestimatorreceiver-app-${{ matrix.number }}'
          slot-name: 'Production'
          package: receiver

      - name: Restart app
        run: |
          az functionapp restart --name 'servicebusestimatorreceiver-app-${{ matrix.number }}' --resource-group ${{ env.RESOURCEGROUPNAME_RECEIVERS }}

  test:
    needs: [ deploy-estimator, deploy-receivers ]
    runs-on: windows-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Execute Stress Test
        shell: pwsh
        run: |
          .\src\Environment\runTests.ps1 -url https://servicebusestimator-app.azurewebsites.net/api/orchestrators/startStressTests -messages ${{ env.MESSAGES }} -min ${{ env.MIN_SIZE }} -max ${{ env.MAX_SIZE }} -resourceGroupName ${{ env.RESOURCEGROUPNAME }} -serviceBusName ${{ env.SERVICEBUSNAME }}

  cleanup:
    needs: test
    runs-on: ubuntu-latest
    environment: cleanup
    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Azure Resource Groups
        run: |
          az group delete -n ${{ env.RESOURCEGROUPNAME }} -y
          az group delete -n ${{ env.RESOURCEGROUPNAME_RECEIVERS }} -y
